### PR TITLE
Fix ignored files issue

### LINKED ISSUE #83: Invalid file paths ignored without any errors or messaging
I have been changing the setup around for an app and ran into an issue when the asset folder name was changed but I forgot to update the eik.json file. The result was no assets and no indication as to what was wrong.

Adding a console.log to https://github.com/eik-lib/common/blob/f102321cca056486f635881d948c0806de37fd63/lib/helpers/local-assets.js#L26 I saw that the invalid path was being silently dropped by the glob.

Perhaps it would be better to log or raise an error if the glob doesn't match any files?

### PR DESCRIPTION
**Pull request by gingermusketeer**
This PR resolves #83.

First it pulls in some modules from eik-lib/cli and then refactors these files so that there is an object to represent the configuration for eik that is stored on the file system.

TODO:
- [x] Cleanup unneeded fixture files
- [x] Refactor files helper to use eik config instead.
- [x] [PR](https://github.com/eik-lib/cli/pull/256) for related cli changes.

### CODE REVIEW

**Comment by trygve-lie** [comment]
Cool.

I am not 100% sure that this belongs here. I honestly think that this code should be in the client. This common package is intended to contain code both the server and client can benefit from sharing. I do not really see what benefit the server will have from any of these.

@digitalsadhu any opinions?

**Comment by digitalsadhu** [comment]
Only argument I have is that these the code could possibly be useful in other tooling such as the internal Eik deploy script. Could just expose it from the client though

**Comment by trygve-lie** [comment]
That's a fair point. Lets keep it here until further notice :+1:

**Comment by trygve-lie** [comment]
@gingermusketeer There is multiple of these:

> File has too many classes (2). Maximum allowed is 1

There should be only one `class` pr file. One can have multiple in common js modules but not in esm (which we will move too soon).

**Comment by gingermusketeer** [comment]
Fixed up the linting issues.  Wanted to get feedback on the approach before fixing them.

> One can have multiple in common js modules but not in esm

@trygve-lie Haven't heard of this before. Is there a limitation in ESM based js for the number of classes?

**Comment by gingermusketeer** [comment]
@digitalsadhu @trygve-lie This is ready for review again

**Review by digitalsadhu — APPROVED** [review]

**Review by trygve-lie — APPROVED** [review]
lgtm :100:

**Comment by trygve-lie** [comment]
@gingermusketeer we're using semantic release in this project so releases is built and published based on commit messages. Would you mind changing the commit to contain a`feat:` and this should be released as a minor version when released.

https://github.com/semantic-release/semantic-release#how-does-it-work

**Comment by gingermusketeer** [comment]
@trygve-lie Happy to do that. Do I need to do it for all the commits or just one?

**Comment by digitalsadhu** [comment]
So long as 1 commit has a feat: that will be enough.

**Comment by gingermusketeer** [comment]
The associated CLI PR is now up for review as well https://github.com/eik-lib/cli/pull/256. I think this should be ready for merging now.

**Comment by digitalsadhu** [comment]
thanks @gingermusketeer !

**Pull request merged**
